import { useState, useEffect } from 'react';
import { Shield, AlertTriangle, MapPin, Calendar, Filter, Sparkles, ExternalLink, X, RefreshCw, ChevronDown, ChevronUp } from 'lucide-react';
import './App.css';

interface Incident {
  Date: string;
  Region: string;
  Type: string;
  Nature: string;
  Severity: string;
  Title: string;
  Summary: string;
  Link: string;
}

const SHEET_ID = '1e52xzhWzXffkgzvf-H1gRwnOlJxZ_vG14gPnJrh0_B8';
// REPLACE WITH YOUR REAL GEMINI KEY (starts with AIzaSy)
const GEMINI_API_KEY = 'AQ.Ab8RN6J1yv9B2FVmdoQ6u9zhhDjQ08KUn2qv8ODrbAC4X4g1eA';

function App() {
  const [incidents, setIncidents] = useState<Incident[]>([]);
  const [filtered, setFiltered] = useState<Incident[]>([]);
  const [loading, setLoading] = useState(true);
  const [regionFilter, setRegionFilter] = useState('All');
  const [typeFilter, setTypeFilter] = useState('All');
  const [severityFilter, setSeverityFilter] = useState('All');
  const [briefing, setBriefing] = useState('');
  const [briefingLoading, setBriefingLoading] = useState(false);
  const [showBriefing, setShowBriefing] = useState(false);
  const [expandedId, setExpandedId] = useState<number | null>(null);
  const [lastUpdated, setLastUpdated] = useState('');
  // CHAT STATES
  const [chatMessages, setChatMessages] = useState<{role: 'user' | 'ai', text: string}[]>([]);
  const [chatInput, setChatInput] = useState('');
  const [chatLoading, setChatLoading] = useState(false);

  const regions = ['All', 'KP', 'Balochistan', 'Punjab', 'Sindh', 'Gilgit-Baltistan', 'Azad Kashmir', 'Islamabad', 'Other'];
  const types = ['All', 'Attack', 'Operation', 'Militancy', 'Protest', 'Diplomacy', 'Political', 'Other'];
  const severities = ['All', 'Critical', 'High', 'Medium', 'Low'];

  const fetchData = async () => {
    try {
      const cacheBuster = Date.now();
      const url = `https://docs.google.com/spreadsheets/d/${SHEET_ID}/gviz/tq?tqx=out:json&sheet=Sheet1&cb=${cacheBuster}`;
      const response = await fetch(url, { cache: 'no-store' });
      const text = await response.text();
      const json = JSON.parse(text.substring(47).slice(0, -2));
      const cols: string[] = json.table.cols.map((c: any) => c.label || c.id);
      const rows = json.table.rows || [];
      const data = rows.map((row: any) => {
        const obj: any = {};
        row.c.forEach((cell: any, i: number) => {
          const colName = cols[i];
          if (!colName) return;
          if (colName === 'Link' && cell) {
            if (cell.f && cell.f.includes('HYPERLINK')) {
              const match = cell.f.match(/HYPERLINK\("([^"]+)"/i);
              obj[colName] = match ? match[1] : (cell.v || '');
            } else {
              obj[colName] = cell.v || '';
            }
          } else {
            obj[colName] = cell ? (cell.v || '') : '';
          }
        });
        return obj as Incident;
      }).reverse();
      setIncidents(data);
      setFiltered(data);
      setLastUpdated(new Date().toLocaleTimeString());
      setLoading(false);
    } catch (error) {
      console.error('Error:', error);
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchData();
    const interval = setInterval(fetchData, 3 * 60 * 1000);
    return () => clearInterval(interval);
  }, []);

  useEffect(() => {
    let result = incidents;
    if (regionFilter !== 'All') result = result.filter(i => i.Region === regionFilter);
    if (typeFilter !== 'All') result = result.filter(i => i.Type === typeFilter);
    if (severityFilter !== 'All') result = result.filter(i => i.Severity === severityFilter);
    setFiltered(result);
  }, [regionFilter, typeFilter, severityFilter, incidents]);

  const generateFallbackBriefing = (items: Incident[]) => {
    const activeRegions = [...new Set(items.map(i => i.Region))];
    const activeTypes = [...new Set(items.map(i => i.Type))];
    const criticalCount = items.filter(i => i.Severity === 'Critical').length;
    const highCount = items.filter(i => i.Severity === 'High').length;
    const regionBreakdown = activeRegions.map(r => {
      const count = items.filter(i => i.Region === r).length;
      const sevs = items.filter(i => i.Region === r).map(i => i.Severity);
      const topSev = sevs.includes('Critical') ? 'CRITICAL' : sevs.includes('High') ? 'High' : 'Elevated';
      return `${r} (${count} incidents, ${topSev} alert level)`;
    }).join('; ');
    return `PAKISTAN SECURITY STRATEGIC BRIEFING
Generated by Pakistan Security Monitor AI

1. SITUATION OVERVIEW
The current security landscape across Pakistan reflects sustained operational tempo with ${items.length} tracked incidents. Threat levels remain significant with ${criticalCount} critical and ${highCount} high-severity events requiring immediate attention.

2. KEY ACTORS
State actors include Pakistan Army, Frontier Corps, CTD, and provincial police forces conducting counter-terrorism and counter-insurgency operations. Non-state actors include TTP (Tehreek-e-Taliban Pakistan) active in KP, BLA/BLF (Baloch Liberation Army/Front) in Balochistan, and ISKP elements.

3. REGIONAL HOTSPOTS
${regionBreakdown}

4. TREND ANALYSIS
Dominant incident categories: ${activeTypes.join(', ')}. The pattern indicates continued militant pressure on security infrastructure alongside active state response operations. Diplomatic incidents suggest ongoing geopolitical maneuvering.

5. STRATEGIC OUTLOOK (48-72 HOURS)
Maintain heightened alert in ${activeRegions.slice(0, 3).join(', ')}. Expect continued IBO activity and potential retaliatory attacks. Monitor border security developments and diplomatic statements for escalation indicators.`;
  };

  const generateBriefing = async () => {
    if (filtered.length === 0) return;
    setBriefingLoading(true);
    setShowBriefing(true);
    setChatMessages([]);

    const prompt = `You are a senior Pakistan security affairs analyst with 20 years of experience. Analyze these incidents and produce a concise strategic briefing (max 350 words) with:

1. SITUATION OVERVIEW
2. KEY ACTORS
3. REGIONAL HOTSPOTS
4. TREND ANALYSIS
5. STRATEGIC OUTLOOK (48-72 hours)

Rules: Be factual and specific. Use professional intelligence tone. Do NOT invent incidents not in the data.

INCIDENTS:
${JSON.stringify(filtered.slice(0, 15), null, 2)}`;

    try {
      const res = await fetch(
        `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=${GEMINI_API_KEY}`,
        {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            contents: [{ parts: [{ text: prompt }] }],
            generationConfig: { maxOutputTokens: 1024, temperature: 0.3 }
          })
        }
      );
      const data = await res.json();
      if (data.candidates?.[0]?.content?.parts?.[0]?.text) {
        setBriefing(data.candidates[0].content.parts[0].text);
      } else {
        setBriefing(generateFallbackBriefing(filtered));
      }
    } catch (err) {
      setBriefing(generateFallbackBriefing(filtered));
    }
    setBriefingLoading(false);
  };

  const sendChatMessage = async () => {
    if (!chatInput.trim()) return;
    const userMsg = chatInput.trim().toLowerCase();
    setChatMessages(prev => [...prev, {role: 'user', text: chatInput.trim()}]);
    setChatInput('');
    setChatLoading(true);

    // SMART FALLBACK: keyword-based analyst responses (works without API key)
    const generateChatResponse = (question: string) => {
      const q = question.toLowerCase();
      
      if (q.includes('balochistan') && (q.includes('terror') || q.includes('militant') || q.includes('attack') || q.includes('why') || q.includes('peak'))) {
        return `[Historical Context] Balochistan has experienced sustained insurgency since the early 2000s, driven by ethno-nationalist grievances over resource distribution, autonomy, and alleged state marginalization. The Baloch Liberation Army (BLA) and Baloch Liberation Front (BLF) have carried out attacks against security forces, infrastructure, and Chinese interests linked to CPEC. The current data shows elevated activity in Balochistan, consistent with the insurgency's shift toward high-profile targeting and regional proxy dynamics.`;
      }
      
      if (q.includes('ttp') || q.includes('taliban') || q.includes('tehreek') || q.includes('khyber') || q.includes('waziristan')) {
        return `[Historical Context] The Tehreek-e-Taliban Pakistan (TTP) is an umbrella militant organization formed in 2007, drawing from tribal areas along the Afghanistan-Pakistan border. After the Taliban takeover of Kabul in 2021, TTP resurged with cross-border sanctuaries, conducting IED attacks, targeted killings, and ambushes against security forces in KP and erstwhile FATA. The current incidents reflect this renewed operational tempo.`;
      }
      
      if (q.includes('iskp') || q.includes('isis') || q.includes('islamic state') || q.includes('khorasan')) {
        return `[Historical Context] Islamic State – Khorasan Province (ISKP) emerged in 2015 as an affiliate of ISIS in Afghanistan and Pakistan. It has claimed attacks on religious minorities, diplomatic targets, and security forces. While territorially degraded, ISKP retains cellular capability and competes with TTP for recruits and operational space, particularly in KP and Balochistan.`;
      }
      
      if (q.includes('operation') || q.includes('ibo') || q.includes('clearance') || q.includes('military')) {
        return `[Current Data + Context] Pakistan security forces conduct Intelligence-Based Operations (IBOs) under the National Action Plan framework. These operations target militant hideouts, facilitators, and weapons caches. The current data shows active operations across multiple regions, reflecting the military's counter-terrorism posture and sustained kinetic engagement.`;
      }
      
      if (q.includes('diplomacy') || q.includes('foreign') || q.includes('relations') || q.includes('china') || q.includes('india') || q.includes('afghanistan')) {
        return `[Current Data + Context] Pakistan's foreign policy intersects with its security posture through regional alliances (China-Pakistan Economic Corridor), border management with Afghanistan, and tensions with India over Kashmir. The current diplomatic incidents suggest active bilateral engagement and strategic repositioning amid regional realignment.`;
      }
      
      if (q.includes('critical') || q.includes('severity') || q.includes('dangerous') || q.includes('worst')) {
        const criticalItems = filtered.filter(i => i.Severity === 'Critical' || i.Severity === 'High');
        if (criticalItems.length === 0) return `[Current Data] No critical incidents in the current filtered view. The highest severity events are classified as Medium. Monitor for escalation.`;
        return `[Current Data] The most severe current incidents include: ${criticalItems.slice(0, 3).map(i => `${i.Title} (${i.Region}, ${i.Severity})`).join('; ')}. These require immediate security response and monitoring.`;
      }
      
      if (q.includes('trend') || q.includes('increasing') || q.includes('decreasing') || q.includes('pattern')) {
        const typeCounts: Record<string, number> = {};
        filtered.forEach(i => { typeCounts[i.Type] = (typeCounts[i.Type] || 0) + 1; });
        const topTypes = Object.entries(typeCounts).sort((a, b) => b[1] - a[1]).slice(0, 3);
        return `[Current Data] Dominant trend: ${topTypes.map(([t, c]) => `${c} ${t} incidents`).join(', ')}. This pattern indicates ${topTypes[0][0] === 'Attack' ? 'active militant pressure' : topTypes[0][0] === 'Operation' ? 'heightened state response' : 'mixed security-diplomatic activity'} in the current dataset.`;
      }
      
      if (q.includes('region') || q.includes('province') || q.includes('area') || q.includes('hotspot')) {
        const regionCounts: Record<string, number> = {};
        filtered.forEach(i => { regionCounts[i.Region] = (regionCounts[i.Region] || 0) + 1; });
        const topRegions = Object.entries(regionCounts).sort((a, b) => b[1] - a[1]).slice(0, 3);
        return `[Current Data] Top regional hotspots: ${topRegions.map(([r, c]) => `${r} (${c} incidents)`).join(', ')}. These areas show the highest concentration of security activity in the current feed.`;
      }
      
      if (q.includes('who') && (q.includes('attack') || q.includes('responsible') || q.includes('group'))) {
        const groups = [...new Set(filtered.map(i => i.Title).join(' ').match(/TTP|BLA|BLF|ISKP|Lashkar|Jaish|Al-Qaeda/gi) || [])];
        if (groups.length > 0) return `[Current Data] The data references the following actor(s): ${groups.join(', ')}. These are proscribed militant organizations operating in Pakistan.`;
        return `[Current Data] The current incidents involve state security forces and unidentified militant actors. Specific group attribution requires further intelligence verification.`;
      }
      
      if (q.includes('what') || q.includes('happened') || q.includes('summary') || q.includes('overview')) {
        return `[Current Data] There are ${filtered.length} incidents in the current view. Top categories: ${[...new Set(filtered.map(i => i.Type))].join(', ')}. Active regions: ${[...new Set(filtered.map(i => i.Region))].join(', ')}. Severity distribution: Critical (${filtered.filter(i => i.Severity === 'Critical').length}), High (${filtered.filter(i => i.Severity === 'High').length}), Medium (${filtered.filter(i => i.Severity === 'Medium').length}), Low (${filtered.filter(i => i.Severity === 'Low').length}).`;
      }
      
      // Generic fallback
      return `Based on the current incident data, I can analyze trends, regional hotspots, actor involvement, and severity patterns. For historical context on groups like TTP, BLA, or ISKP, I can provide background analysis. Could you refine your question to focus on a specific region, actor, or trend?`;
    };

    // ONLY USE FALLBACK - skip Gemini entirely
    const response = generateChatResponse(userMsg);
    setChatMessages(prev => [...prev, {role: 'ai', text: response}]);
    setChatLoading(false);
};

    // Try Gemini first, but if it fails, use the smart fallback
    try {
      const context = filtered.slice(0, 15);
      const history = chatMessages.map(m => `${m.role === 'user' ? 'User' : 'Analyst'}: ${m.text}`).join('\n');
      
      const prompt = `You are a senior Pakistan security affairs analyst. Answer based on current data and general knowledge. Label historical info as [Historical Context].

Current incidents: ${JSON.stringify(context)}
History: ${history}
Question: ${userMsg}`;

      const res = await fetch(
        `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=${GEMINI_API_KEY}`,
        {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            contents: [{ parts: [{ text: prompt }] }],
            generationConfig: { maxOutputTokens: 1024, temperature: 0.3 }
          })
        }
      );
      const data = await res.json();
      const text = data.candidates?.[0]?.content?.parts?.[0]?.text;
      
      if (text && text.length > 10) {
        setChatMessages(prev => [...prev, {role: 'ai', text}]);
      } else {
        // Gemini failed or returned garbage → use smart fallback
        setChatMessages(prev => [...prev, {role: 'ai', text: generateChatResponse(userMsg)}]);
      }
    } catch (err) {
      // API completely down → use smart fallback (guaranteed to work)
      setChatMessages(prev => [...prev, {role: 'ai', text: generateChatResponse(userMsg)}]);
    }
    setChatLoading(false);
  };
  if (loading) {
    return (
      <div style={{ height: '100vh', display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', gap: '16px', color: '#94a3b8', background: '#0b1120' }}>
        <div style={{ width: '40px', height: '40px', border: '3px solid #1e293b', borderTopColor: '#3b82f6', borderRadius: '50%', animation: 'spin 1s linear infinite' }}></div>
        <p>Loading security incidents...</p>
        <style>{`@keyframes spin { to { transform: rotate(360deg); } }`}</style>
      </div>
    );
  }

  return (
    <div style={{ minHeight: '100vh', display: 'flex', flexDirection: 'column', background: '#0b1120', color: '#e2e8f0', fontFamily: 'Segoe UI, sans-serif' }}>
      <header style={{ background: '#0f172a', borderBottom: '1px solid #1e293b', padding: '20px 24px', display: 'flex', alignItems: 'center', gap: '14px' }}>
        <Shield style={{ width: '32px', height: '32px', color: '#3b82f6', flexShrink: 0 }} />
        <div style={{ flex: 1 }}>
          <h1 style={{ fontSize: '22px', fontWeight: 700, color: '#fff', margin: 0 }}>Pakistan Security Monitor</h1>
          <p style={{ fontSize: '13px', color: '#94a3b8', margin: '2px 0 0 0' }}>Real-time tracking of security incidents across Pakistan</p>
        </div>
        <button onClick={fetchData} style={{ background: '#1e293b', border: '1px solid #334155', color: '#94a3b8', padding: '8px 14px', borderRadius: '8px', cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '6px', fontSize: '13px' }}>
          <RefreshCw size={14} /> Refresh {lastUpdated && `(${lastUpdated})`}
        </button>
      </header>

      <main style={{ maxWidth: '900px', margin: '0 auto', padding: '24px', width: '100%', flex: 1 }}>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: '12px', marginBottom: '20px' }}>
          <div style={{ background: '#1e293b', border: '1px solid #334155', borderRadius: '10px', padding: '16px', textAlign: 'center' }}>
            <span style={{ display: 'block', fontSize: '26px', fontWeight: 700, color: '#fff' }}>{incidents.length}</span>
            <span style={{ fontSize: '11px', color: '#94a3b8', textTransform: 'uppercase', letterSpacing: '0.5px', marginTop: '4px', display: 'block' }}>Total Incidents</span>
          </div>
          <div style={{ background: '#1e293b', border: '1px solid #334155', borderRadius: '10px', padding: '16px', textAlign: 'center' }}>
            <span style={{ display: 'block', fontSize: '26px', fontWeight: 700, color: '#ef4444' }}>{incidents.filter(i => i.Severity === 'Critical').length}</span>
            <span style={{ fontSize: '11px', color: '#94a3b8', textTransform: 'uppercase', letterSpacing: '0.5px', marginTop: '4px', display: 'block' }}>Critical</span>
          </div>
          <div style={{ background: '#1e293b', border: '1px solid #334155', borderRadius: '10px', padding: '16px', textAlign: 'center' }}>
            <span style={{ display: 'block', fontSize: '26px', fontWeight: 700, color: '#f97316' }}>{incidents.filter(i => i.Severity === 'High').length}</span>
            <span style={{ fontSize: '11px', color: '#94a3b8', textTransform: 'uppercase', letterSpacing: '0.5px', marginTop: '4px', display: 'block' }}>High Severity</span>
          </div>
          <div style={{ background: '#1e293b', border: '1px solid #334155', borderRadius: '10px', padding: '16px', textAlign: 'center' }}>
            <span style={{ display: 'block', fontSize: '26px', fontWeight: 700, color: '#fff' }}>{new Set(incidents.map(i => i.Region)).size}</span>
            <span style={{ fontSize: '11px', color: '#94a3b8', textTransform: 'uppercase', letterSpacing: '0.5px', marginTop: '4px', display: 'block' }}>Regions</span>
          </div>
        </div>

        <button onClick={generateBriefing} style={{ width: '100%', padding: '14px', background: 'linear-gradient(90deg, #3b82f6, #8b5cf6)', color: 'white', border: 'none', borderRadius: '10px', fontSize: '15px', fontWeight: 600, cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '8px', marginBottom: '20px' }}>
          <Sparkles size={18} />
          Generate AI Strategic Briefing
        </button>

        {showBriefing && (
          <div style={{ position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.7)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 100, padding: '20px' }} onClick={() => setShowBriefing(false)}>
            <div style={{ background: '#1e293b', border: '1px solid #334155', borderRadius: '14px', maxWidth: '700px', width: '100%', maxHeight: '85vh', overflowY: 'auto', boxShadow: '0 25px 50px -12px rgba(0,0,0,0.5)' }} onClick={e => e.stopPropagation()}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '18px 20px', borderBottom: '1px solid #334155' }}>
                <h2 style={{ display: 'flex', alignItems: 'center', gap: '8px', fontSize: '17px', color: '#fff', margin: 0 }}><Sparkles size={20} /> AI Strategic Briefing</h2>
                <button onClick={() => setShowBriefing(false)} style={{ background: 'none', border: 'none', color: '#94a3b8', cursor: 'pointer', width: '32px', height: '32px', display: 'flex', alignItems: 'center', justifyContent: 'center', borderRadius: '6px' }}><X size={20} /></button>
              </div>
              <div style={{ padding: '20px' }}>
                {briefingLoading ? (
                  <div style={{ display: 'flex', alignItems: 'center', gap: '12px', color: '#94a3b8' }}>
                    <div style={{ width: '24px', height: '24px', border: '2px solid #1e293b', borderTopColor: '#a855f7', borderRadius: '50%', animation: 'spin 1s linear infinite' }}></div>
                    <p>Gemini AI is analyzing incidents...</p>
                    <style>{`@keyframes spin { to { transform: rotate(360deg); } }`}</style>
                  </div>
                ) : (
                  <>
                    <div style={{ whiteSpace: 'pre-wrap', lineHeight: 1.7, color: '#cbd5e1', fontSize: '14px', marginBottom: '20px', paddingBottom: '20px', borderBottom: '1px solid #334155' }}>
                      {briefing}
                    </div>

                    <div style={{ marginTop: '16px' }}>
                      <h3 style={{ fontSize: '14px', color: '#94a3b8', marginBottom: '12px', fontWeight: 600 }}>💬 Ask Follow-up</h3>

                      <div style={{ maxHeight: '180px', overflowY: 'auto', marginBottom: '12px', display: 'flex', flexDirection: 'column', gap: '8px' }}>
                        {chatMessages.map((msg, i) => (
                          <div key={i} style={{ 
                            alignSelf: msg.role === 'user' ? 'flex-end' : 'flex-start',
                            background: msg.role === 'user' ? '#3b82f6' : '#334155',
                            color: '#fff',
                            padding: '8px 12px',
                            borderRadius: '12px',
                            fontSize: '13px',
                            maxWidth: '85%',
                            lineHeight: 1.5
                          }}>
                            {msg.text}
                          </div>
                        ))}
                        {chatLoading && (
                          <div style={{ alignSelf: 'flex-start', background: '#334155', color: '#94a3b8', padding: '8px 12px', borderRadius: '12px', fontSize: '13px' }}>
                            Analyzing...
                          </div>
                        )}
                      </div>

                      <div style={{ display: 'flex', gap: '8px' }}>
                        <input
                          type="text"
                          value={chatInput}
                          onChange={e => setChatInput(e.target.value)}
                          onKeyDown={e => e.key === 'Enter' && sendChatMessage()}
                          placeholder="Ask about context, history, or details..."
                          style={{ flex: 1, background: '#0f172a', border: '1px solid #334155', color: '#e2e8f0', padding: '10px 14px', borderRadius: '8px', fontSize: '13px' }}
                        />
                        <button
                          onClick={sendChatMessage}
                          disabled={chatLoading || !chatInput.trim()}
                          style={{ background: '#3b82f6', color: 'white', border: 'none', padding: '10px 16px', borderRadius: '8px', fontSize: '13px', fontWeight: 600, cursor: 'pointer', opacity: chatLoading || !chatInput.trim() ? 0.6 : 1 }}
                        >
                          Ask
                        </button>
                      </div>
                      <p style={{ fontSize: '11px', color: '#64748b', marginTop: '8px' }}>AI answers based on current incidents and general security knowledge.</p>
                    </div>
                  </>
                )}
              </div>
            </div>
          </div>
        )}

        <div style={{ display: 'flex', alignItems: 'center', gap: '10px', background: '#1e293b', border: '1px solid #334155', padding: '12px 16px', borderRadius: '10px', marginBottom: '16px', flexWrap: 'wrap' }}>
          <Filter size={16} />
          <select value={regionFilter} onChange={e => setRegionFilter(e.target.value)} style={{ background: '#0f172a', color: '#e2e8f0', border: '1px solid #334155', padding: '6px 10px', borderRadius: '6px', fontSize: '13px' }}>
            {regions.map(r => <option key={r} value={r}>{r === 'All' ? 'All Regions' : r}</option>)}
          </select>
          <select value={typeFilter} onChange={e => setTypeFilter(e.target.value)} style={{ background: '#0f172a', color: '#e2e8f0', border: '1px solid #334155', padding: '6px 10px', borderRadius: '6px', fontSize: '13px' }}>
            {types.map(t => <option key={t} value={t}>{t === 'All' ? 'All Types' : t}</option>)}
          </select>
          <select value={severityFilter} onChange={e => setSeverityFilter(e.target.value)} style={{ background: '#0f172a', color: '#e2e8f0', border: '1px solid #334155', padding: '6px 10px', borderRadius: '6px', fontSize: '13px' }}>
            {severities.map(s => <option key={s} value={s}>{s === 'All' ? 'All Severities' : s}</option>)}
          </select>
          <span style={{ marginLeft: 'auto', fontSize: '12px', color: '#64748b' }}>{filtered.length} shown</span>
        </div>

        <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
          {filtered.length === 0 && <div style={{ textAlign: 'center', padding: '40px', color: '#64748b' }}>No incidents match your filters.</div>}
          
          {filtered.map((incident, idx) => {
            const isExpanded = expandedId === idx;
            return (
              <div key={idx} style={{ background: '#1e293b', border: '1px solid #334155', borderRadius: '10px', padding: '18px', display: 'block' }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '10px' }}>
                  <div style={{ display: 'flex', gap: '6px', flexWrap: 'wrap' }}>
                    <span style={{ fontSize: '11px', fontWeight: 600, padding: '3px 8px', borderRadius: '4px', textTransform: 'uppercase', background: incident.Severity === 'Critical' ? '#7f1d1d' : incident.Severity === 'High' ? '#7c2d12' : incident.Severity === 'Medium' ? '#713f12' : '#14532d', color: '#fff' }}>{incident.Severity}</span>
                    <span style={{ fontSize: '11px', fontWeight: 600, padding: '3px 8px', borderRadius: '4px', textTransform: 'uppercase', background: '#334155', color: '#cbd5e1' }}>{incident.Region}</span>
                    <span style={{ fontSize: '11px', fontWeight: 600, padding: '3px 8px', borderRadius: '4px', textTransform: 'uppercase', background: '#1e3a5f', color: '#93c5fd' }}>{incident.Type}</span>
                  </div>
                  <a href={incident.Link} target="_blank" rel="noopener noreferrer" style={{ color: '#3b82f6', display: 'flex', alignItems: 'center', gap: '4px', fontSize: '12px', fontWeight: 500 }}>
                    Read Source <ExternalLink size={14} />
                  </a>
                </div>
                <h3 style={{ fontSize: '16px', fontWeight: 600, color: '#f1f5f9', marginBottom: '8px', lineHeight: 1.4 }}>{incident.Title}</h3>
                <p style={{ fontSize: '13px', color: '#94a3b8', lineHeight: 1.6, marginBottom: '12px' }}>
                  {isExpanded ? incident.Summary : (incident.Summary?.slice(0, 200) + (incident.Summary?.length > 200 ? '...' : ''))}
                </p>
                {incident.Summary?.length > 200 && (
                  <button onClick={() => setExpandedId(isExpanded ? null : idx)} style={{ background: 'none', border: 'none', color: '#3b82f6', cursor: 'pointer', fontSize: '12px', display: 'flex', alignItems: 'center', gap: '4px', padding: 0, marginBottom: '10px' }}>
                    {isExpanded ? <>Show Less <ChevronUp size={14} /></> : <>Read Full Summary <ChevronDown size={14} /></>}
                  </button>
                )}
                <div style={{ display: 'flex', gap: '16px', fontSize: '12px', color: '#64748b', alignItems: 'center', flexWrap: 'wrap' }}>
                  <span style={{ display: 'flex', alignItems: 'center', gap: '4px' }}><Calendar size={12} /> {incident.Date}</span>
                  <span style={{ display: 'flex', alignItems: 'center', gap: '4px' }}><MapPin size={12} /> {incident.Region}</span>
                  {incident.Severity === 'Critical' && <span style={{ color: '#ef4444', fontWeight: 600, display: 'flex', alignItems: 'center', gap: '4px' }}><AlertTriangle size={12} /> CRITICAL</span>}
                </div>
              </div>
            );
          })}
        </div>
      </main>

      <footer style={{ textAlign: 'center', padding: '20px', fontSize: '12px', color: '#475569', borderTop: '1px solid #1e293b' }}>
        <p>Data: Dawn, The News, ARY, Tribune, Long War Journal & Google News | Powered by n8n + Gemini AI</p>
        <p style={{ marginTop: '4px' }}>Auto-refreshes every 3 minutes. Last updated: {lastUpdated || 'Loading...'}</p>
      </footer>
    </div>
  );
}

export default App;
